name: Auto Assign Action
on:
  - pull_request_target

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Auto-assign reviewers and assignees
        uses: kentaro-m/auto-assign-action@v1.2.4
        with:
          configuration-path: '.github/auto_assign.yml'
