name: Check Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: ['main']
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run lint
        working-directory: .
