name: Issue PR Labeler

on:
  issues:
    types:
      - opened
      - edited
  pull_request:
    types:
      - opened
      - reopened
      - edited

jobs:
  labeling:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Run Issue PR Labeler
        uses: hoho4190/issue-pr-labeler@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          disable-bot: true
          config-file-name: labeler-config.yaml

  add_reviewers:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          configuration-path: '.github/auto-assign.yml'
